### ISSUE TITLE
how did you generated the keys.dart file 

### ISSUE THREAD

**Issue by haleem13** [hmziqrs/invmovieconcept1#71]
Hi there,
could you please tell me how you generated the keys.dart files, as it say keys.dart file was auto generated.
Could you please tell me to generate Keys.dart file???

**Comment by hmziqrs** [comment]
Hey @haleem13, There are a bunch of dart CLI-based scripts in the `scripts` directory.

Solution:
Execute this command in the project's root directory in terminal `dart scripts/genIntlKeys.dart`

Context:
- `keys.dart` is part of my custom internationalization strings management system.
- `keys.dart` is generated as a sibling of `strings.dart` (If `strings.dart` exist in a `messages` directory)
- Although the messages directory can exist anywhere in the `lib` directory. The script will identify and generate the `keys.dart`
